import type {
  Session,
  HandHistory,
  Player,
  PlayerStats,
} from "@/types/poker";

export const mockPlayers: Player[] = [
  {
    id: "p1",
    name: "Takeshi M.",
    role: "leader",
    joinedAt: "2024-01-15",
  },
  {
    id: "p2",
    name: "Yuki S.",
    role: "member",
    joinedAt: "2024-02-01",
  },
  {
    id: "p3",
    name: "Ryo K.",
    role: "member",
    joinedAt: "2024-03-10",
  },
  {
    id: "p4",
    name: "Haruto T.",
    role: "member",
    joinedAt: "2024-04-20",
  },
];

export const mockSessions: Session[] = [
  {
    id: "s1",
    date: "2025-02-01",
    startTime: "20:00",
    endTime: "02:30",
    venue: "live",
    location: "Tokyo Poker Club",
    gameType: "NLH",
    stakes: "1/2",
    buyIn: 300,
    cashOut: 785,
    profit: 485,
    durationMinutes: 390,
    notes: "テーブルが非常にルースだった。バリューベットを多めに。",
    playerId: "p1",
    createdAt: "2025-02-01T20:00:00Z",
    updatedAt: "2025-02-02T02:30:00Z",
  },
  {
    id: "s2",
    date: "2025-01-28",
    startTime: "19:00",
    endTime: "23:45",
    venue: "online",
    location: "PokerStars",
    gameType: "NLH",
    stakes: "0.5/1",
    buyIn: 200,
    cashOut: 142,
    profit: -58,
    durationMinutes: 285,
    notes: "ティルト気味だった。ブレイクをもっと取るべきだった。",
    playerId: "p1",
    createdAt: "2025-01-28T19:00:00Z",
    updatedAt: "2025-01-29T00:00:00Z",
  },
  {
    id: "s3",
    date: "2025-01-25",
    startTime: "21:00",
    endTime: "03:00",
    venue: "live",
    location: "Yokohama Casino Bar",
    gameType: "PLO",
    stakes: "1/2",
    buyIn: 500,
    cashOut: 1230,
    profit: 730,
    durationMinutes: 360,
    notes: "PLOでナッツを引き続けた。非常に良いセッション。",
    playerId: "p1",
    createdAt: "2025-01-25T21:00:00Z",
    updatedAt: "2025-01-26T03:00:00Z",
  },
  {
    id: "s4",
    date: "2025-01-22",
    startTime: "22:00",
    endTime: "01:30",
    venue: "online",
    location: "GGPoker",
    gameType: "NLH",
    stakes: "0.25/0.5",
    buyIn: 100,
    cashOut: 88,
    profit: -12,
    durationMinutes: 210,
    notes: "ショートセッション。特に大きなハンドなし。",
    playerId: "p1",
    createdAt: "2025-01-22T22:00:00Z",
    updatedAt: "2025-01-23T01:30:00Z",
  },
  {
    id: "s5",
    date: "2025-01-18",
    startTime: "20:00",
    endTime: "04:00",
    venue: "live",
    location: "Tokyo Poker Club",
    gameType: "NLH",
    stakes: "2/5",
    buyIn: 500,
    cashOut: 1450,
    profit: 950,
    durationMinutes: 480,
    notes: "キープレイヤーのリークを特定。3BETレンジを広げて成功。",
    playerId: "p1",
    createdAt: "2025-01-18T20:00:00Z",
    updatedAt: "2025-01-19T04:00:00Z",
  },
  {
    id: "s6",
    date: "2025-01-15",
    startTime: "19:30",
    endTime: "00:30",
    venue: "live",
    location: "Osaka Card Room",
    gameType: "NLH",
    stakes: "1/2",
    buyIn: 300,
    cashOut: 195,
    profit: -105,
    durationMinutes: 300,
    notes: "クーラーが多かった。セットオーバーセットで大きくロスト。",
    playerId: "p1",
    createdAt: "2025-01-15T19:30:00Z",
    updatedAt: "2025-01-16T00:30:00Z",
  },
  {
    id: "s7",
    date: "2025-01-12",
    startTime: "21:00",
    endTime: "02:00",
    venue: "online",
    location: "PokerStars",
    gameType: "NLH",
    stakes: "0.5/1",
    buyIn: 200,
    cashOut: 365,
    profit: 165,
    durationMinutes: 300,
    notes: "堅実にプレイ。ブラフキャッチが上手くいった。",
    playerId: "p1",
    createdAt: "2025-01-12T21:00:00Z",
    updatedAt: "2025-01-13T02:00:00Z",
  },
  {
    id: "s8",
    date: "2025-01-08",
    startTime: "20:00",
    endTime: "01:00",
    venue: "live",
    location: "Tokyo Poker Club",
    gameType: "NLH",
    stakes: "1/2",
    buyIn: 300,
    cashOut: 520,
    profit: 220,
    durationMinutes: 300,
    notes: "ポジションを意識したプレイが奏功。",
    playerId: "p1",
    createdAt: "2025-01-08T20:00:00Z",
    updatedAt: "2025-01-09T01:00:00Z",
  },
  {
    id: "s9",
    date: "2025-01-05",
    startTime: "18:00",
    endTime: "22:30",
    venue: "online",
    location: "GGPoker",
    gameType: "PLO",
    stakes: "0.5/1",
    buyIn: 200,
    cashOut: 310,
    profit: 110,
    durationMinutes: 270,
    notes: "PLOの練習セッション。ハンドセレクションを改善。",
    playerId: "p1",
    createdAt: "2025-01-05T18:00:00Z",
    updatedAt: "2025-01-05T22:30:00Z",
  },
  {
    id: "s10",
    date: "2025-01-02",
    startTime: "21:00",
    endTime: "03:30",
    venue: "live",
    location: "Tokyo Poker Club",
    gameType: "NLH",
    stakes: "2/5",
    buyIn: 500,
    cashOut: 320,
    profit: -180,
    durationMinutes: 390,
    notes: "新年で酔ったプレイヤーが多かったが、自分もコンディション悪かった。",
    playerId: "p1",
    createdAt: "2025-01-02T21:00:00Z",
    updatedAt: "2025-01-03T03:30:00Z",
  },
];

export const mockHands: HandHistory[] = [
  {
    id: "h1",
    sessionId: "s1",
    date: "2025-02-01",
    gameType: "NLH",
    stakes: "1/2",
    heroPosition: "BTN",
    heroCards: [
      { rank: "A", suit: "s" },
      { rank: "K", suit: "h" },
    ],
    streets: [
      {
        street: "preflop",
        actions: [
          { position: "UTG", action: "fold", isHero: false },
          { position: "MP", action: "raise", amount: 6, isHero: false },
          { position: "CO", action: "fold", isHero: false },
          { position: "BTN", action: "3bet", amount: 18, isHero: true },
          { position: "SB", action: "fold", isHero: false },
          { position: "BB", action: "fold", isHero: false },
          { position: "MP", action: "call", amount: 18, isHero: false },
        ],
        potSize: 39,
        board: [],
        thoughtProcess:
          "MPのオープンレンジは広め。AKsはBTNから3BETしてイニシアチブを取る。4BETされたらコールかフォールドのミックス戦略。",
      },
      {
        street: "flop",
        actions: [
          { position: "MP", action: "check", isHero: false },
          { position: "BTN", action: "bet", amount: 25, isHero: true },
          { position: "MP", action: "call", amount: 25, isHero: false },
        ],
        potSize: 89,
        board: [
          { rank: "A", suit: "d" },
          { rank: "7", suit: "c" },
          { rank: "3", suit: "s" },
        ],
        thoughtProcess:
          "トップペアトップキッカーをヒット。ドライボードなのでポットの2/3サイズでバリューベット。相手のコールレンジはAx, 77, ポケットペア。",
      },
      {
        street: "turn",
        actions: [
          { position: "MP", action: "check", isHero: false },
          { position: "BTN", action: "bet", amount: 60, isHero: true },
          { position: "MP", action: "call", amount: 60, isHero: false },
        ],
        potSize: 209,
        board: [
          { rank: "A", suit: "d" },
          { rank: "7", suit: "c" },
          { rank: "3", suit: "s" },
          { rank: "T", suit: "h" },
        ],
        thoughtProcess:
          "ターンのTはあまりテクスチャーを変えない。引き続きバリューベット。相手がまだコールしてくるならAQ, AJ, ATあたり。",
      },
      {
        street: "river",
        actions: [
          { position: "MP", action: "check", isHero: false },
          { position: "BTN", action: "bet", amount: 100, isHero: true },
          { position: "MP", action: "call", amount: 100, isHero: false },
        ],
        potSize: 409,
        board: [
          { rank: "A", suit: "d" },
          { rank: "7", suit: "c" },
          { rank: "3", suit: "s" },
          { rank: "T", suit: "h" },
          { rank: "2", suit: "d" },
        ],
        thoughtProcess:
          "リバーは2dでブランク。3ストリートのバリューベットで相手のAx系からマックスバリューを取る。オーバーベットも検討したが、相手のコールレンジを考慮してポットの半分程度に。",
      },
    ],
    pot: 409,
    result: 203,
    tags: ["VALUE_BET", "3BET", "CONFIDENT", "KEY_HAND"],
    notes: "典型的な3BETポットでのバリューライン。全ストリートでバリューを取り切った。",
    playerId: "p1",
    createdAt: "2025-02-01T21:30:00Z",
    updatedAt: "2025-02-01T21:30:00Z",
  },
  {
    id: "h2",
    sessionId: "s1",
    date: "2025-02-01",
    gameType: "NLH",
    stakes: "1/2",
    heroPosition: "CO",
    heroCards: [
      { rank: "Q", suit: "h" },
      { rank: "J", suit: "h" },
    ],
    streets: [
      {
        street: "preflop",
        actions: [
          { position: "UTG", action: "fold", isHero: false },
          { position: "MP", action: "fold", isHero: false },
          { position: "CO", action: "raise", amount: 6, isHero: true },
          { position: "BTN", action: "call", amount: 6, isHero: false },
          { position: "SB", action: "fold", isHero: false },
          { position: "BB", action: "call", amount: 6, isHero: false },
        ],
        potSize: 19,
        board: [],
        thoughtProcess:
          "QJsはCOからスタンダードオープン。マルチウェイになる可能性があるが、ポジションとスートの強みで参加。",
      },
      {
        street: "flop",
        actions: [
          { position: "BB", action: "check", isHero: false },
          { position: "CO", action: "bet", amount: 12, isHero: true },
          { position: "BTN", action: "fold", isHero: false },
          { position: "BB", action: "raise", amount: 35, isHero: false },
          { position: "CO", action: "call", amount: 35, isHero: true },
        ],
        potSize: 89,
        board: [
          { rank: "T", suit: "h" },
          { rank: "9", suit: "h" },
          { rank: "4", suit: "c" },
        ],
        thoughtProcess:
          "フラッシュドローとオープンエンドストレートドロー。BBのチェックレイズに対して、ドローイングハンドとしてコール。フォールドエクイティがあればレイズも検討だが、マルチウェイだったのでフラットコール。",
      },
      {
        street: "turn",
        actions: [
          { position: "BB", action: "bet", amount: 65, isHero: false },
          { position: "CO", action: "call", amount: 65, isHero: true },
        ],
        potSize: 219,
        board: [
          { rank: "T", suit: "h" },
          { rank: "9", suit: "h" },
          { rank: "4", suit: "c" },
          { rank: "K", suit: "d" },
        ],
        thoughtProcess:
          "Kが落ちてストレートが完成。ここでスロープレイするかレイズするか。相手のベットサイズ的にまだバリューハンドで打っている可能性が高いのでコールしてリバーでバリューを最大化。",
      },
      {
        street: "river",
        actions: [
          { position: "BB", action: "bet", amount: 90, isHero: false },
          { position: "CO", action: "raise", amount: 220, isHero: true },
          { position: "BB", action: "call", amount: 220, isHero: false },
        ],
        potSize: 659,
        board: [
          { rank: "T", suit: "h" },
          { rank: "9", suit: "h" },
          { rank: "4", suit: "c" },
          { rank: "K", suit: "d" },
          { rank: "3", suit: "h" },
        ],
        thoughtProcess:
          "リバーでフラッシュも完成！ナッツフラッシュ。相手のベットに対してレイズ。相手はセットやツーペアでコールする可能性が高い。フラッシュに見えにくいラインなのでバリューレイズ。",
      },
    ],
    pot: 659,
    result: 439,
    tags: ["SLOW_PLAY", "VALUE_BET", "GREAT_PLAY", "TEAM_SHARE"],
    notes:
      "ストレートからフラッシュに改善したドリームハンド。スロープレイのタイミングが完璧だった。チーム共有推奨。",
    playerId: "p1",
    createdAt: "2025-02-01T23:15:00Z",
    updatedAt: "2025-02-01T23:15:00Z",
  },
  {
    id: "h3",
    sessionId: "s2",
    date: "2025-01-28",
    gameType: "NLH",
    stakes: "0.5/1",
    heroPosition: "BB",
    heroCards: [
      { rank: "8", suit: "d" },
      { rank: "8", suit: "c" },
    ],
    streets: [
      {
        street: "preflop",
        actions: [
          { position: "CO", action: "raise", amount: 2.5, isHero: false },
          { position: "BTN", action: "call", amount: 2.5, isHero: false },
          { position: "SB", action: "fold", isHero: false },
          { position: "BB", action: "call", amount: 2.5, isHero: true },
        ],
        potSize: 8,
        board: [],
        thoughtProcess:
          "88はBBからマルチウェイでセットマイニング。インプライドオッズは十分。",
      },
      {
        street: "flop",
        actions: [
          { position: "BB", action: "check", isHero: true },
          { position: "CO", action: "bet", amount: 5, isHero: false },
          { position: "BTN", action: "call", amount: 5, isHero: false },
          { position: "BB", action: "call", amount: 5, isHero: true },
        ],
        potSize: 23,
        board: [
          { rank: "8", suit: "h" },
          { rank: "5", suit: "s" },
          { rank: "2", suit: "d" },
        ],
        thoughtProcess:
          "セットヒット！ドライボードなのでスロープレイ。チェックコールでポットをビルドしつつ、相手にブラフする機会を与える。",
      },
      {
        street: "turn",
        actions: [
          { position: "BB", action: "check", isHero: true },
          { position: "CO", action: "bet", amount: 15, isHero: false },
          { position: "BTN", action: "fold", isHero: false },
          { position: "BB", action: "raise", amount: 42, isHero: true },
          { position: "CO", action: "all-in", amount: 90, isHero: false },
          { position: "BB", action: "call", amount: 90, isHero: true },
        ],
        potSize: 218,
        board: [
          { rank: "8", suit: "h" },
          { rank: "5", suit: "s" },
          { rank: "2", suit: "d" },
          { rank: "6", suit: "h" },
        ],
        thoughtProcess:
          "ターンで6が落ちてストレートの可能性が出てきたが、セットはまだ非常に強い。チェックレイズでバリューを最大化。相手のオールインは喜んでコール。74sは可能性としてあるが、レンジ全体では大きくアヘッド。",
      },
    ],
    pot: 218,
    result: -100,
    tags: ["CHECK_RAISE", "TILT_CHECK", "MISTAKE", "SOLVER_NEEDED"],
    notes:
      "セットオーバーセットでバッドビート。相手は55でフロップでセット。ターンのチェックレイズのサイジングを再検討する必要あり。結果は悪いがプレイ自体は検討の余地あり。",
    playerId: "p1",
    createdAt: "2025-01-28T20:45:00Z",
    updatedAt: "2025-01-28T20:45:00Z",
  },
];

export const mockStats: PlayerStats = {
  totalSessions: mockSessions.length,
  totalHands: 2847,
  totalProfit: mockSessions.reduce((sum, s) => sum + s.profit, 0),
  totalHours: Math.round(
    mockSessions.reduce((sum, s) => sum + s.durationMinutes, 0) / 60
  ),
  hourlyRate: Math.round(
    (mockSessions.reduce((sum, s) => sum + s.profit, 0) /
      mockSessions.reduce((sum, s) => sum + s.durationMinutes, 0)) *
      60
  ),
  winRate: Math.round(
    (mockSessions.filter((s) => s.profit > 0).length / mockSessions.length) *
      100
  ),
  bbPer100: 8.3,
  bestSession: Math.max(...mockSessions.map((s) => s.profit)),
  worstSession: Math.min(...mockSessions.map((s) => s.profit)),
  currentStreak: 3,
  profitByGameType: {
    NLH: mockSessions
      .filter((s) => s.gameType === "NLH")
      .reduce((sum, s) => sum + s.profit, 0),
    PLO: mockSessions
      .filter((s) => s.gameType === "PLO")
      .reduce((sum, s) => sum + s.profit, 0),
    PLO5: 0,
    Mixed: 0,
  },
  profitByVenue: {
    live: mockSessions
      .filter((s) => s.venue === "live")
      .reduce((sum, s) => sum + s.profit, 0),
    online: mockSessions
      .filter((s) => s.venue === "online")
      .reduce((sum, s) => sum + s.profit, 0),
  },
  monthlyProfit: [
    { month: "2024-08", profit: 320 },
    { month: "2024-09", profit: -150 },
    { month: "2024-10", profit: 680 },
    { month: "2024-11", profit: 450 },
    { month: "2024-12", profit: -200 },
    { month: "2025-01", profit: 1820 },
    { month: "2025-02", profit: 485 },
  ],
};

export const teamMemberStats: Record<string, PlayerStats> = {
  p1: mockStats,
  p2: {
    ...mockStats,
    totalProfit: 1250,
    hourlyRate: 18,
    winRate: 55,
    bbPer100: 5.2,
    monthlyProfit: [
      { month: "2024-08", profit: 150 },
      { month: "2024-09", profit: 200 },
      { month: "2024-10", profit: -100 },
      { month: "2024-11", profit: 300 },
      { month: "2024-12", profit: 180 },
      { month: "2025-01", profit: 420 },
      { month: "2025-02", profit: 100 },
    ],
  },
  p3: {
    ...mockStats,
    totalProfit: -320,
    hourlyRate: -5,
    winRate: 40,
    bbPer100: -2.1,
    monthlyProfit: [
      { month: "2024-08", profit: 80 },
      { month: "2024-09", profit: -250 },
      { month: "2024-10", profit: 100 },
      { month: "2024-11", profit: -180 },
      { month: "2024-12", profit: -70 },
      { month: "2025-01", profit: 50 },
      { month: "2025-02", profit: -50 },
    ],
  },
  p4: {
    ...mockStats,
    totalProfit: 890,
    hourlyRate: 12,
    winRate: 52,
    bbPer100: 4.5,
    monthlyProfit: [
      { month: "2024-08", profit: 200 },
      { month: "2024-09", profit: 50 },
      { month: "2024-10", profit: 150 },
      { month: "2024-11", profit: 120 },
      { month: "2024-12", profit: 80 },
      { month: "2025-01", profit: 190 },
      { month: "2025-02", profit: 100 },
    ],
  },
};
