import { PrismaClient } from "@prisma/client";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";

const adapter = new PrismaBetterSqlite3({ url: "file:dev.db" });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("🦐 Seeding Ebi-Hub database...");

  // ===== Team =====
  const team = await prisma.team.create({
    data: {
      id: "team-ebi",
      name: "Ebi-Hub Osaka",
    },
  });
  console.log("  ✓ Team created:", team.name);

  // ===== Spots (Osaka) =====
  const spots = [
    {
      id: "roots",
      name: "ROOTS OSAKA",
      shortName: "ROOTS",
      area: "心斎橋",
      stakes: JSON.stringify(["100/200", "200/400", "500/1000"]),
      gameTypes: JSON.stringify(["NLH", "PLO"]),
      category: "cash",
      playerPool: "mixed",
      notes: "大阪の定番。フロアが広く、レギュラーが多い。深夜帯はルースプレイヤーが増える。",
    },
    {
      id: "poker-live",
      name: "POKER LIVE OSAKA",
      shortName: "PLO",
      area: "難波",
      stakes: JSON.stringify(["100/200", "200/400"]),
      gameTypes: JSON.stringify(["NLH"]),
      category: "cash",
      playerPool: "loose",
      notes: "初心者やカジュアルプレイヤーが多い。バリューベットが効きやすい環境。",
    },
    {
      id: "ggpl",
      name: "GGPL OSAKA",
      shortName: "GGPL",
      area: "梅田",
      stakes: JSON.stringify(["100/200", "200/400", "500/1000"]),
      gameTypes: JSON.stringify(["NLH", "PLO"]),
      category: "cash",
      playerPool: "mixed",
      notes: "梅田エリアの大型店。トーナメントも定期開催。",
    },
    {
      id: "blow",
      name: "BLOW",
      shortName: "BLOW",
      area: "心斎橋",
      stakes: JSON.stringify(["100/200", "200/400"]),
      gameTypes: JSON.stringify(["NLH"]),
      category: "amusement",
      playerPool: "loose",
      notes: "アミューズメント。初心者が多くテーブルセレクション次第で稼ぎやすい。",
    },
    {
      id: "zeus",
      name: "ゼウス",
      shortName: "ゼウス",
      area: "難波",
      stakes: JSON.stringify(["50/100", "100/200"]),
      gameTypes: JSON.stringify(["NLH"]),
      category: "amusement",
      playerPool: "loose",
      notes: "低ステークスが中心。ビギナーフレンドリー。練習に最適。",
    },
    {
      id: "universe",
      name: "UNIVERSE",
      shortName: "UNI",
      area: "梅田",
      stakes: JSON.stringify(["100/200", "200/400"]),
      gameTypes: JSON.stringify(["NLH", "PLO"]),
      category: "cash",
      playerPool: "tight",
      notes: "レギュラーが多くタイトなテーブル。エクスプロイトしにくいが良い練習環境。",
    },
    {
      id: "jerrys",
      name: "Jerrys",
      shortName: "Jerry",
      area: "心斎橋",
      stakes: JSON.stringify(["100/200", "200/400"]),
      gameTypes: JSON.stringify(["NLH"]),
      category: "amusement",
      playerPool: "mixed",
      notes: "落ち着いた雰囲気。常連客とのコミュニケーションが取りやすい。",
    },
    {
      id: "white",
      name: "WHITE",
      shortName: "WHITE",
      area: "難波",
      stakes: JSON.stringify(["100/200"]),
      gameTypes: JSON.stringify(["NLH"]),
      category: "amusement",
      playerPool: "loose",
      notes: "小規模だがアットホーム。週末は混雑する。",
    },
    {
      id: "guild",
      name: "ギルド",
      shortName: "ギルド",
      area: "心斎橋",
      stakes: JSON.stringify(["100/200", "200/400"]),
      gameTypes: JSON.stringify(["NLH", "PLO"]),
      category: "cash",
      playerPool: "mixed",
      notes: "トーナメントシリーズの開催実績あり。イベント時は特に盛り上がる。",
    },
    {
      id: "casino-stadium",
      name: "Casino Stadium",
      shortName: "CS",
      area: "心斎橋",
      stakes: JSON.stringify(["100/200", "200/400", "500/1000"]),
      gameTypes: JSON.stringify(["NLH", "PLO"]),
      category: "cash",
      playerPool: "mixed",
      notes: "大型店舗。ハイステークスも常設。トーナメントシリーズのホスト実績多数。",
    },
    {
      id: "iris",
      name: "IRis",
      shortName: "IRis",
      area: "梅田",
      stakes: JSON.stringify(["100/200", "200/400"]),
      gameTypes: JSON.stringify(["NLH"]),
      category: "amusement",
      playerPool: "loose",
      notes: "梅田の隠れ家的スポット。カジュアルプレイヤーが多い。",
    },
    {
      id: "jackpot",
      name: "Jackpot",
      shortName: "JP",
      area: "難波",
      stakes: JSON.stringify(["100/200", "200/400"]),
      gameTypes: JSON.stringify(["NLH", "PLO"]),
      category: "cash",
      playerPool: "mixed",
      notes: "難波エリアの老舗。常連プレイヤーのコミュニティが強い。",
    },
    {
      id: "backdoor",
      name: "BACKDOOR",
      shortName: "BD",
      area: "心斎橋",
      stakes: JSON.stringify(["100/200"]),
      gameTypes: JSON.stringify(["NLH"]),
      category: "amusement",
      playerPool: "loose",
      notes: "バー併設のアミューズメントポーカー。初心者にも優しい。",
    },
  ];

  for (const spot of spots) {
    await prisma.spot.create({ data: spot });
  }
  console.log(`  ✓ ${spots.length} Osaka spots created`);

  // ===== Users =====
  const users = [
    {
      id: "p1",
      name: "おにく",
      role: "admin",
      status: "on-fire",
      joinedAt: new Date("2024-01-15"),
      teamId: team.id,
      primarySpotId: "roots",
    },
    {
      id: "p2",
      name: "タカ",
      role: "member",
      status: "active",
      joinedAt: new Date("2024-02-01"),
      teamId: team.id,
      primarySpotId: "ggpl",
    },
    {
      id: "p3",
      name: "モッチ",
      role: "member",
      status: "active",
      joinedAt: new Date("2024-03-10"),
      teamId: team.id,
      primarySpotId: "casino-stadium",
    },
    {
      id: "p4",
      name: "ノセ",
      role: "member",
      status: "on-fire",
      joinedAt: new Date("2024-04-05"),
      teamId: team.id,
      primarySpotId: "poker-live",
    },
    {
      id: "p5",
      name: "便座",
      role: "member",
      status: "cooling-down",
      joinedAt: new Date("2024-05-12"),
      teamId: team.id,
      primarySpotId: "blow",
    },
    {
      id: "p6",
      name: "ロキソニン陸斗",
      role: "member",
      status: "active",
      joinedAt: new Date("2024-06-20"),
      teamId: team.id,
      primarySpotId: "jackpot",
      notes: "門真代表",
    },
    {
      id: "p7",
      name: "だーふく",
      role: "member",
      status: "resting",
      joinedAt: new Date("2024-07-08"),
      teamId: team.id,
      primarySpotId: "universe",
    },
    {
      id: "p8",
      name: "コロッケ",
      role: "member",
      status: "active",
      joinedAt: new Date("2024-08-15"),
      teamId: team.id,
      primarySpotId: "guild",
    },
    {
      id: "p9",
      name: "ぱいぱんコニー",
      role: "member",
      status: "active",
      joinedAt: new Date("2024-09-01"),
      teamId: team.id,
      primarySpotId: "iris",
    },
  ];

  for (const user of users) {
    await prisma.user.create({ data: user });
  }
  console.log(`  ✓ ${users.length} team members created`);

  // ===== Sessions =====
  const sessions = [
    {
      id: "s1",
      sessionDate: "2025-02-01",
      startTime: "20:00",
      endTime: "02:30",
      startDatetime: new Date("2025-02-01T20:00:00Z"),
      venue: "live",
      location: "ROOTS OSAKA",
      gameType: "NLH",
      stakes: "100/200",
      buyIn: 300,
      cashOut: 785,
      profit: 485,
      currency: "USD",
      exchangeRate: 150,
      buyInJpy: 45000,
      cashOutJpy: 117750,
      profitJpy: 72750,
      status: "SETTLED",
      durationMinutes: 390,
      notes: "テーブルが非常にルースだった。バリューベットを多めに。",
      playerId: "p1",
      spotId: "roots",
    },
    {
      id: "s2",
      sessionDate: "2025-01-28",
      startTime: "19:00",
      endTime: "23:45",
      startDatetime: new Date("2025-01-28T19:00:00Z"),
      venue: "online",
      location: "PokerStars",
      gameType: "NLH",
      stakes: "0.5/1",
      buyIn: 200,
      cashOut: 142,
      profit: -58,
      currency: "USD",
      exchangeRate: 150,
      buyInJpy: 30000,
      cashOutJpy: 21300,
      profitJpy: -8700,
      status: "SETTLED",
      durationMinutes: 285,
      notes: "ティルト気味だった。ブレイクをもっと取るべきだった。",
      playerId: "p2",
    },
    {
      id: "s3",
      sessionDate: "2025-01-25",
      startTime: "21:00",
      endTime: "03:00",
      startDatetime: new Date("2025-01-25T21:00:00Z"),
      venue: "live",
      location: "Casino Stadium",
      gameType: "NLH",
      stakes: "200/400",
      buyIn: 500,
      cashOut: 920,
      profit: 420,
      currency: "USD",
      exchangeRate: 150,
      buyInJpy: 75000,
      cashOutJpy: 138000,
      profitJpy: 63000,
      status: "SETTLED",
      durationMinutes: 360,
      notes: "テーブルセレクションが良かった。フィッシュが2人いた。",
      playerId: "p3",
      spotId: "casino-stadium",
    },
    {
      id: "s4",
      sessionDate: "2025-01-22",
      startTime: "19:30",
      endTime: "01:00",
      startDatetime: new Date("2025-01-22T19:30:00Z"),
      venue: "live",
      location: "POKER LIVE OSAKA",
      gameType: "NLH",
      stakes: "100/200",
      buyIn: 300,
      cashOut: 680,
      profit: 380,
      currency: "USD",
      exchangeRate: 150,
      buyInJpy: 45000,
      cashOutJpy: 102000,
      profitJpy: 57000,
      status: "SETTLED",
      durationMinutes: 330,
      notes: "好調。3BETポットでバリューを取り切れた。",
      playerId: "p4",
      spotId: "poker-live",
    },
    {
      id: "s5",
      sessionDate: "2025-01-18",
      startTime: "20:00",
      endTime: "04:00",
      startDatetime: new Date("2025-01-18T20:00:00Z"),
      venue: "live",
      location: "GGPL OSAKA",
      gameType: "NLH",
      stakes: "200/400",
      buyIn: 500,
      cashOut: 1450,
      profit: 950,
      currency: "USD",
      exchangeRate: 150,
      buyInJpy: 75000,
      cashOutJpy: 217500,
      profitJpy: 142500,
      status: "SETTLED",
      durationMinutes: 480,
      notes: "キープレイヤーのリークを特定。3BETレンジを広げて成功。",
      playerId: "p1",
      spotId: "ggpl",
    },
    {
      id: "s6",
      sessionDate: "2025-01-15",
      startTime: "19:30",
      endTime: "00:30",
      startDatetime: new Date("2025-01-15T19:30:00Z"),
      venue: "live",
      location: "POKER LIVE OSAKA",
      gameType: "NLH",
      stakes: "100/200",
      buyIn: 300,
      cashOut: 195,
      profit: -105,
      currency: "USD",
      exchangeRate: 150,
      buyInJpy: 45000,
      cashOutJpy: 29250,
      profitJpy: -15750,
      status: "SETTLED",
      durationMinutes: 300,
      notes: "クーラーが多かった。セットオーバーセットで大きくロスト。",
      playerId: "p4",
      spotId: "poker-live",
    },
    {
      id: "s7",
      sessionDate: "2025-01-20",
      startTime: "18:00",
      endTime: "23:30",
      startDatetime: new Date("2025-01-20T18:00:00Z"),
      venue: "live",
      location: "Jackpot",
      gameType: "NLH",
      stakes: "100/200",
      buyIn: 200,
      cashOut: 355,
      profit: 155,
      currency: "USD",
      exchangeRate: 150,
      buyInJpy: 30000,
      cashOutJpy: 53250,
      profitJpy: 23250,
      status: "SETTLED",
      durationMinutes: 330,
      notes: "常連テーブルでじっくり。タイトイメージを利用してブラフ成功。",
      playerId: "p6",
      spotId: "jackpot",
    },
    {
      id: "s8",
      sessionDate: "2025-01-08",
      startTime: "20:00",
      endTime: "01:00",
      startDatetime: new Date("2025-01-08T20:00:00Z"),
      venue: "live",
      location: "BLOW",
      gameType: "NLH",
      stakes: "100/200",
      buyIn: 300,
      cashOut: 520,
      profit: 220,
      currency: "USD",
      exchangeRate: 150,
      buyInJpy: 45000,
      cashOutJpy: 78000,
      profitJpy: 33000,
      status: "SETTLED",
      durationMinutes: 300,
      notes: "ポジションを意識したプレイが奏功。",
      playerId: "p5",
      spotId: "blow",
    },
    {
      id: "s9",
      sessionDate: "2025-02-03",
      startTime: "20:00",
      endTime: "02:30",
      startDatetime: new Date("2025-02-03T20:00:00Z"),
      venue: "live",
      location: "IRis",
      gameType: "NLH",
      stakes: "100/200",
      buyIn: 200,
      cashOut: 410,
      profit: 210,
      currency: "USD",
      exchangeRate: 150,
      buyInJpy: 30000,
      cashOutJpy: 61500,
      profitJpy: 31500,
      status: "SETTLED",
      durationMinutes: 390,
      notes: "カジュアルテーブルでバリュー重視。安定したセッション。",
      playerId: "p9",
      spotId: "iris",
    },
    {
      id: "s10",
      sessionDate: "2025-02-05",
      startTime: "19:00",
      endTime: "00:00",
      startDatetime: new Date("2025-02-05T19:00:00Z"),
      venue: "live",
      location: "ギルド",
      gameType: "NLH",
      stakes: "200/400",
      buyIn: 400,
      cashOut: 280,
      profit: -120,
      currency: "USD",
      exchangeRate: 150,
      buyInJpy: 60000,
      cashOutJpy: 42000,
      profitJpy: -18000,
      status: "SETTLED",
      durationMinutes: 300,
      notes: "レギュラー卓で苦戦。リバーブラフを2回キャッチされた。",
      playerId: "p8",
      spotId: "guild",
    },
    {
      id: "s11",
      sessionDate: "2024-12-28",
      startTime: "20:00",
      endTime: "02:00",
      startDatetime: new Date("2024-12-28T20:00:00Z"),
      venue: "live",
      location: "Jerrys",
      gameType: "NLH",
      stakes: "100/200",
      buyIn: 30000,
      cashOut: 52000,
      profit: 22000,
      currency: "JPY",
      exchangeRate: 1,
      buyInJpy: 30000,
      cashOutJpy: 52000,
      profitJpy: 22000,
      status: "SETTLED",
      durationMinutes: 360,
      notes: "円建てライブ。テーブルのレベルが低く、安定して勝てた。",
      playerId: "p1",
      spotId: "jerrys",
    },
  ];

  for (const session of sessions) {
    await prisma.session.create({ data: session });
  }
  console.log(`  ✓ ${sessions.length} sessions created`);

  // ===== Opponent Notes =====
  const opponentNotes = [
    {
      opponentName: "山田さん",
      spotId: "roots",
      tags: JSON.stringify(["CALLING_STATION", "WEAK_POSTFLOP"]),
      notes: "プリフロップは広くコール。フロップ以降はペアがないと降りる。2バレルで落ちやすい。",
      stakes: "100/200",
      lastSeen: "2025-02-01",
      createdBy: "p1",
    },
    {
      opponentName: "Kenさん",
      spotId: "roots",
      tags: JSON.stringify(["REG", "TAG", "POSITIONAL_AWARE"]),
      notes: "堅いレギュラー。IPからのCBET頻度が高い。OOPではチェックレイズが多い。3BETレンジは狭い。",
      stakes: "200/400",
      lastSeen: "2025-01-25",
      createdBy: "p1",
    },
    {
      opponentName: "マサ",
      spotId: "poker-live",
      tags: JSON.stringify(["FISH", "TILT_PRONE"]),
      notes: "ルースパッシブ。大きなポットを負けるとティルト気味になる。ティルト時はブラフキャッチが増える。",
      stakes: "100/200",
      lastSeen: "2025-01-28",
      createdBy: "p4",
    },
    {
      opponentName: "タツヤ",
      spotId: "ggpl",
      tags: JSON.stringify(["LAG", "BLUFF_HEAVY", "OVERBET_FREQ"]),
      notes: "アグレッシブなLAG。リバーのオーバーベットが多いがブラフ頻度も高い。コールダウンが有効。",
      stakes: "200/400",
      lastSeen: "2025-02-03",
      createdBy: "p2",
    },
    {
      opponentName: "ユウキ先輩",
      spotId: "blow",
      tags: JSON.stringify(["NITS", "SLOW_PLAY_HEAVY"]),
      notes: "極端にタイト。プリフロップのレンジが非常に狭い。レイズにはモンスター警戒。スロープレイ多用。",
      stakes: "100/200",
      lastSeen: "2025-01-20",
      createdBy: "p5",
    },
    {
      opponentName: "ヒロ",
      spotId: "casino-stadium",
      tags: JSON.stringify(["REG", "LAG", "AGGRESSIVE_POSTFLOP"]),
      notes: "CSの常連LAG。ポストフロップが上手い。3BETポットでのCB頻度が高い。ブラフレンジ広め。",
      stakes: "200/400",
      lastSeen: "2025-01-25",
      createdBy: "p3",
    },
    {
      opponentName: "シンジ",
      spotId: "jackpot",
      tags: JSON.stringify(["CALLING_STATION", "PASSIVE"]),
      notes: "コールドコールが非常に多い。ベットサイズを上げてバリューを取るべき。",
      stakes: "100/200",
      lastSeen: "2025-01-20",
      createdBy: "p6",
    },
  ];

  for (const note of opponentNotes) {
    await prisma.opponentNote.create({ data: note });
  }
  console.log(`  ✓ ${opponentNotes.length} opponent notes created`);

  // ===== Activity Feed =====
  const activities = [
    {
      type: "session_end",
      title: "セッション終了",
      detail: "ROOTS OSAKA — +¥72,750 (6.5時間)",
      metadata: JSON.stringify({ sessionId: "s1", profitJpy: 72750 }),
      userId: "p1",
      createdAt: new Date("2025-02-02T02:30:00Z"),
    },
    {
      type: "hand_review",
      title: "ハンドレビュー投稿",
      detail: "AKs 3BETポット — バリューライン成功",
      metadata: JSON.stringify({ handId: "h1", tags: ["VALUE_BET", "3BET"] }),
      userId: "p1",
      createdAt: new Date("2025-02-02T10:00:00Z"),
    },
    {
      type: "comment",
      title: "コメント追加",
      detail: "「フロップのCBサイズは2/3より1/2の方がGTO的には良いかも」",
      metadata: JSON.stringify({ handId: "h1", commentId: "c1" }),
      userId: "p2",
      createdAt: new Date("2025-02-02T10:00:00Z"),
    },
    {
      type: "opponent_note",
      title: "相手メモ更新",
      detail: "タツヤ @ GGPL — LAG, ブラフ多い",
      metadata: JSON.stringify({ opponentName: "タツヤ", spotId: "ggpl" }),
      userId: "p2",
      createdAt: new Date("2025-02-03T15:00:00Z"),
    },
    {
      type: "session_start",
      title: "セッション開始",
      detail: "GGPL OSAKA — NLH 200/400",
      metadata: JSON.stringify({ spotId: "ggpl", stakes: "200/400" }),
      userId: "p1",
      createdAt: new Date("2025-01-18T20:00:00Z"),
    },
    {
      type: "session_end",
      title: "セッション終了",
      detail: "GGPL OSAKA — +¥142,500 (8時間)",
      metadata: JSON.stringify({ sessionId: "s5", profitJpy: 142500 }),
      userId: "p1",
      createdAt: new Date("2025-01-19T04:00:00Z"),
    },
    {
      type: "hand_review",
      title: "ハンドレビュー投稿",
      detail: "QJh ナッツフラッシュ — スロープレイ成功",
      metadata: JSON.stringify({ handId: "h2", tags: ["SLOW_PLAY", "GREAT_PLAY"] }),
      userId: "p3",
      createdAt: new Date("2025-02-02T14:00:00Z"),
    },
    {
      type: "session_end",
      title: "セッション終了",
      detail: "POKER LIVE OSAKA — -¥15,750 (5時間)",
      metadata: JSON.stringify({ sessionId: "s6", profitJpy: -15750 }),
      userId: "p4",
      createdAt: new Date("2025-01-16T00:30:00Z"),
    },
    {
      type: "comment",
      title: "コメント追加",
      detail: "「ターンのスロープレイは最高の判断」",
      metadata: JSON.stringify({ handId: "h2", commentId: "c4" }),
      userId: "p8",
      createdAt: new Date("2025-02-02T12:00:00Z"),
    },
    {
      type: "session_start",
      title: "セッション開始",
      detail: "BLOW — NLH 100/200",
      metadata: JSON.stringify({ spotId: "blow", stakes: "100/200" }),
      userId: "p5",
      createdAt: new Date("2025-02-07T21:00:00Z"),
    },
    {
      type: "session_end",
      title: "セッション終了",
      detail: "Casino Stadium — +¥63,000 (6時間)",
      metadata: JSON.stringify({ sessionId: "s3", profitJpy: 63000 }),
      userId: "p3",
      createdAt: new Date("2025-01-26T03:00:00Z"),
    },
    {
      type: "session_end",
      title: "セッション終了",
      detail: "Jackpot — +¥23,250 (5.5時間)",
      metadata: JSON.stringify({ sessionId: "s7", profitJpy: 23250 }),
      userId: "p6",
      createdAt: new Date("2025-01-20T23:30:00Z"),
    },
    {
      type: "session_end",
      title: "セッション終了",
      detail: "IRis — +¥31,500 (6.5時間)",
      metadata: JSON.stringify({ sessionId: "s9", profitJpy: 31500 }),
      userId: "p9",
      createdAt: new Date("2025-02-04T02:30:00Z"),
    },
    {
      type: "session_end",
      title: "セッション終了",
      detail: "ギルド — -¥18,000 (5時間)",
      metadata: JSON.stringify({ sessionId: "s10", profitJpy: -18000 }),
      userId: "p8",
      createdAt: new Date("2025-02-06T00:00:00Z"),
    },
    {
      type: "opponent_note",
      title: "相手メモ追加",
      detail: "ヒロ @ Casino Stadium — LAG, ポストフロップ上手い",
      metadata: JSON.stringify({ opponentName: "ヒロ", spotId: "casino-stadium" }),
      userId: "p3",
      createdAt: new Date("2025-01-26T10:00:00Z"),
    },
  ];

  for (const activity of activities) {
    await prisma.activity.create({ data: activity });
  }
  console.log(`  ✓ ${activities.length} activity feed entries created`);

  // ===== Tournaments (Major Events) =====
  const tournaments = [
    {
      name: "KOPT #12 Main Event",
      series: "KOPT",
      startDate: "2025-02-15",
      endDate: "2025-02-16",
      registrationEnd: "2025-02-15T14:00",
      buyInJpy: 15000,
      guaranteeJpy: 5000000,
      gameType: "NLH",
      format: "re-entry",
      accentColor: "#FFD700",
      status: "upcoming",
      notes: "KOPT第12回メインイベント。Day1 3フライト制。",
      spotId: "roots",
    },
    {
      name: "TPC Osaka Championship",
      series: "TPC",
      startDate: "2025-02-22",
      endDate: "2025-02-23",
      registrationEnd: "2025-02-22T13:00",
      buyInJpy: 20000,
      guaranteeJpy: 8000000,
      gameType: "NLH",
      format: "freezeout",
      accentColor: "#2563EB",
      status: "upcoming",
      notes: "TPC大阪チャンピオンシップ。フリーズアウト形式。",
      spotId: "ggpl",
    },
    {
      name: "JAPAN GOLD DRAGON Osaka Leg",
      series: "JAPAN_GOLD_DRAGON",
      startDate: "2025-03-01",
      endDate: "2025-03-02",
      registrationEnd: "2025-03-01T15:00",
      buyInJpy: 30000,
      guaranteeJpy: 10000000,
      gameType: "NLH",
      format: "re-entry",
      accentColor: "#DC2626",
      status: "upcoming",
      notes: "ジャパンゴールドドラゴン大阪レッグ。優勝者はグランドファイナル出場権獲得。",
      spotId: "roots",
    },
    {
      name: "OSL Season 5 Day 2",
      series: "OSL",
      startDate: "2025-02-08",
      registrationEnd: "2025-02-08T18:00",
      buyInJpy: 5000,
      guaranteeJpy: 500000,
      gameType: "NLH",
      format: "bounty",
      accentColor: "#00FF9F",
      status: "registration_open",
      notes: "OSLシーズン5 Day2。バウンティ形式。今夜開催！",
      spotId: "ggpl",
    },
    {
      name: "ROOTS Saturday Deepstack",
      series: "OTHER",
      startDate: "2025-02-08",
      registrationEnd: "2025-02-08T19:30",
      buyInJpy: 8000,
      guaranteeJpy: 300000,
      gameType: "NLH",
      format: "deepstack",
      accentColor: "#F59E0B",
      status: "registration_open",
      notes: "毎週土曜開催のディープスタック。レイト飛込みOK。",
      spotId: "roots",
    },
    {
      name: "ギルド Monthly Championship",
      series: "OTHER",
      startDate: "2025-02-09",
      registrationEnd: "2025-02-09T14:00",
      buyInJpy: 10000,
      guaranteeJpy: 1000000,
      gameType: "NLH",
      format: "freezeout",
      accentColor: "#8B5CF6",
      status: "upcoming",
      notes: "ギルド月例チャンピオンシップ。フリーズアウト。",
      spotId: "guild",
    },
    {
      name: "JOPT Grand Final Osaka Qualifier",
      series: "JOPT",
      startDate: "2025-03-08",
      endDate: "2025-03-09",
      registrationEnd: "2025-03-08T12:00",
      buyInJpy: 25000,
      guaranteeJpy: 15000000,
      gameType: "NLH",
      format: "re-entry",
      accentColor: "#FF6B35",
      status: "upcoming",
      notes: "JOPTグランドファイナル大阪予選。優勝者は東京GFへの出場権＋旅費サポート。",
      spotId: "casino-stadium",
    },
  ];

  for (const tournament of tournaments) {
    await prisma.tournament.create({ data: tournament });
  }
  console.log(`  ✓ ${tournaments.length} tournaments created`);

  // ===== Daily Events (Today's schedule) =====
  const dailyEvents = [
    {
      date: "2025-02-08",
      title: "NLH キャッシュゲーム 100/200",
      startTime: "14:00",
      endTime: "05:00",
      eventType: "cash_game",
      detail: "常設キャッシュゲーム。2テーブル開放。",
      spotId: "roots",
    },
    {
      date: "2025-02-08",
      title: "Saturday Deepstack トーナメント",
      startTime: "19:00",
      endTime: "23:00",
      eventType: "tournament",
      buyInJpy: 8000,
      detail: "毎週土曜のディープスタック。25000チップスタート。",
      spotId: "roots",
    },
    {
      date: "2025-02-08",
      title: "NLH キャッシュ 100/200",
      startTime: "15:00",
      endTime: "03:00",
      eventType: "cash_game",
      detail: "アフタヌーンキャッシュ開放。",
      spotId: "poker-live",
    },
    {
      date: "2025-02-08",
      title: "OSL Season 5 Day 2 バウンティ",
      startTime: "18:00",
      endTime: "23:00",
      eventType: "tournament",
      buyInJpy: 5000,
      detail: "OSLバウンティトーナメント。1キル500円バック。",
      spotId: "ggpl",
    },
    {
      date: "2025-02-08",
      title: "NLH/PLO ミックスゲーム",
      startTime: "16:00",
      endTime: "01:00",
      eventType: "cash_game",
      detail: "NLH/PLOローテーション。200/400メイン。",
      spotId: "ggpl",
    },
    {
      date: "2025-02-08",
      title: "フリーロール土曜大会",
      startTime: "15:00",
      endTime: "18:00",
      eventType: "freeroll",
      buyInJpy: 0,
      detail: "参加費無料。優勝者に次回トーナメントシート進呈。",
      spotId: "blow",
    },
    {
      date: "2025-02-08",
      title: "ビギナーズNLH 50/100",
      startTime: "14:00",
      endTime: "20:00",
      eventType: "cash_game",
      detail: "初心者向け低ステークス。ディーラーが丁寧に説明。",
      spotId: "zeus",
    },
    {
      date: "2025-02-08",
      title: "PLO キャッシュ 200/400",
      startTime: "18:00",
      endTime: "02:00",
      eventType: "cash_game",
      detail: "PLO専用テーブル。PLO好き集合。",
      spotId: "universe",
    },
    {
      date: "2025-02-08",
      title: "サタデーナイトNLH 100/200",
      startTime: "20:00",
      endTime: "04:00",
      eventType: "cash_game",
      detail: "土曜の夜は最も人が集まる時間帯。",
      spotId: "jerrys",
    },
    {
      date: "2025-02-08",
      title: "ギルド リーグ戦 Week 6",
      startTime: "17:00",
      endTime: "22:00",
      eventType: "league",
      buyInJpy: 3000,
      detail: "月間リーグ戦。ポイント上位にプライズ。",
      spotId: "guild",
    },
    {
      date: "2025-02-08",
      title: "NLH ハイステークス 500/1000",
      startTime: "19:00",
      endTime: "04:00",
      eventType: "cash_game",
      detail: "土曜夜のハイステークスキャッシュ。3テーブル開放予定。",
      spotId: "casino-stadium",
    },
    {
      date: "2025-02-08",
      title: "CS サタデートーナメント",
      startTime: "15:00",
      endTime: "20:00",
      eventType: "tournament",
      buyInJpy: 10000,
      detail: "Casino Stadium土曜定例トーナメント。ディープスタック形式。",
      spotId: "casino-stadium",
    },
    {
      date: "2025-02-08",
      title: "IRis カジュアルNLH 100/200",
      startTime: "16:00",
      endTime: "00:00",
      eventType: "cash_game",
      detail: "梅田の隠れ家でまったりキャッシュゲーム。初心者歓迎。",
      spotId: "iris",
    },
    {
      date: "2025-02-08",
      title: "IRis 女性限定フリーロール",
      startTime: "14:00",
      endTime: "16:00",
      eventType: "freeroll",
      buyInJpy: 0,
      detail: "女性プレイヤー限定のフリーロール。参加者にドリンク1杯サービス。",
      spotId: "iris",
    },
    {
      date: "2025-02-08",
      title: "Jackpot NLH/PLO キャッシュ",
      startTime: "17:00",
      endTime: "03:00",
      eventType: "cash_game",
      detail: "NLHとPLOのテーブルを同時開放。常連多め。",
      spotId: "jackpot",
    },
    {
      date: "2025-02-08",
      title: "Jackpot サタデーバウンティ",
      startTime: "20:00",
      endTime: "23:30",
      eventType: "tournament",
      buyInJpy: 5000,
      detail: "土曜夜のバウンティトーナメント。1キル300円バック。",
      spotId: "jackpot",
    },
    {
      date: "2025-02-08",
      title: "BACKDOOR ナイトNLH 100/200",
      startTime: "19:00",
      endTime: "02:00",
      eventType: "cash_game",
      detail: "バー併設のカジュアルキャッシュゲーム。ドリンク片手にポーカー。",
      spotId: "backdoor",
    },
    {
      date: "2025-02-08",
      title: "BACKDOOR ビギナーズレッスン＆フリープレイ",
      startTime: "15:00",
      endTime: "18:00",
      eventType: "freeroll",
      buyInJpy: 0,
      detail: "初心者向けレッスン付きフリープレイ。ポーカーデビューに最適。",
      spotId: "backdoor",
    },
  ];

  for (const event of dailyEvents) {
    await prisma.dailyEvent.create({ data: event });
  }
  console.log(`  ✓ ${dailyEvents.length} daily events created`);

  console.log("\n🦐 Ebi-Hub seed complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
